PKG_NAME=ndn-riot
PKG_URL=https://github.com/named-data-iot/ndn-riot
PKG_VERSION=37e5a95d72b19ae6ea690e5e51d162530d4045f8
PKG_LICENSE=LGPLv2.1

.PHONY: all

all:
	"$(MAKE)" -C $(PKG_BUILDDIR)

include $(RIOTBASE)/pkg/pkg.mk
